- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
Deep down, aren't we all Microsoft shills?
Fixes: #34
> Basic .vscode config

- .github/main.workflow
> remove seekret because github actions interprets flow wrong

- .circleci/config.yml
- jest.config.js
- junit.xml
- package-lock.json
- package.json
> CircleCI test reporting

- package-lock.json
- package.json
- src/client/routes/manage/HackerTable.tsx
> Fix some type errors

- src/server/index.ts
Looks like this was changed and caused build errors
> Fix dotenv require and config

- src/server/api/UserRouter.ts
- src/server/auth.ts
- src/server/index.ts
- src/server/resolvers/HackerResolver.ts
Fix logger calls to not use `logger.log`
> Fix logger calls

- package.json
Don't need b/c we have tests now
> Remove pass with no tests option in jest ci

- package-lock.json
- package.json
Update marked to fix medium npm audit error.
> fixed typedoc audit errors

- src/server/resolvers/index.ts
Currently if applicant started application but did not manually hit submit button, `started` status is not set.
> Show application as started for auto-submit

- package-lock.json
> Auto-fixed vulns

- src/client/routes/dashboard/HackerDash.tsx
- src/client/routes/dashboard/dashboards.graphql.ts
- src/client/routes/manage/ActionRenderer.tsx
- src/common/schema.graphql.ts
- src/server/resolvers/index.ts
> Add declined hacker option

- __snapshots__/client/components/Sidebar/Sidebar.test.tsx.snap
- __snapshots__/client/routes/dashboard/Frame.test.tsx.snap
- src/client/routes/nfc/NfcTable.tsx
> Make nfc page mobile friendly

- codegen.json
- src/client/assets/routes.js
- src/common/schema.graphql.ts
- src/server/resolvers/helpers.ts
- src/server/resolvers/index.ts
The way this is meant to work is that volunteers who are scanning NFC will be assigned a `usertype.volunteer`
> Add volunteer type for NFC/event scanning

- src/client/contexts/TableContext.ts
- src/client/routes/nfc/NfcTable.tsx
- src/client/routes/nfc/NfcTableRows.tsx
- src/client/routes/nfc/Row.tsx
- src/client/routes/nfc/helpers.ts
* Enable click-to-select of the NFC table hackers
* Use Fuse.js for fuzzy searching in the NFC table
* Tweak global fuzzy search opts to have a threshold of 0.2
> NFC niceties

- __snapshots__/client/components/Sidebar/Sidebar.test.tsx.snap
- __snapshots__/client/routes/dashboard/Frame.test.tsx.snap
- src/client/assets/routes.js
- webpack.common.js
* Add content-hash to bundles
* Lazy load all code paths not related to login (esp. because it reloads completely after login)
> Optimize bundles

- src/client/routes/nfc/NfcTable.tsx
- src/client/routes/nfc/NfcTableRows.tsx
- src/server/events/index.test.ts
- src/server/events/index.ts
- src/server/resolvers/index.ts
> Move event type parsing to description

- src/client/assets/strings.json
- src/client/routes/manage/ActionRenderer.tsx
- src/client/routes/manage/HackerTable.test.tsx
- src/client/routes/manage/HackerTable.tsx
- src/client/routes/manage/HackerTableRows.tsx
- src/client/routes/manage/ManageHackers.tsx
- src/client/routes/manage/ResumeLink.tsx
- src/client/routes/manage/SponsorHackerView.tsx
- src/client/routes/manage/sponsor.graphql.ts
- src/client/routes/manageSponsor/CreateSponsor.tsx
- src/client/routes/nfc/Nfc.tsx
- src/server/nfc/index.ts
- src/server/resolvers/index.ts
Added permissions to allow sponsors to view hacker table and scan NFC
> Sponsor hacker view

- src/client/routes/nfc/Nfc.tsx
increase to 1hr before + after
> Increase NFC filter buffer

- src/client/routes/manage/HackerTable.tsx
- src/server/resolvers/index.ts
Backported from sponsor hacker table
> Add multiple events filter to hackertable

- src/server/events/index.ts
Prevent scrubbing of [Booth] type events so that sponsor booth events will not be deleted by hard sync even if they are not present in the calendar.
> Sponsor booth allowance

- .env.template
- src/client/routes/manage/ManageHackers.tsx
- src/client/routes/manage/SponsorHackerView.tsx
- src/server/index.ts
- src/server/resolvers/helpers.ts
- src/server/resolvers/index.ts
- disable playground in prod
- add CORS in prod
- hide internal server error details from clients
- add authorization checks to common critical plural queries (checkIns, companies, hackers, teams, tiers, sponsors, mentors, organizers)
Fixes #136
> Fix several security issues

- src/client/routes/dashboard/OrganizerDash.tsx
- src/client/routes/manage/SponsorHackerView.tsx
- src/server/auth/helpers.ts
- src/server/events/index.ts
- src/server/index.ts
- src/server/nfc/index.ts
- src/server/resolvers/index.ts
- add logging for a lot of funcs
- make createTier, createSponsor, createCompany use 1 db call instead of 2
- add unique name checks to createTier, createCompany
- set explicit cookie settings
> Refactor createTier, createSponsor, createCompany + add logging

- __snapshots__/client/components/Sidebar/Sidebar.test.tsx.snap
- __snapshots__/client/routes/dashboard/Frame.test.tsx.snap
- __snapshots__/client/routes/login/Login.test.tsx.snap
- __snapshots__/client/routes/profile/Profile.test.tsx.snap
- package.json
- src/client/routes/login/Login.tsx
- src/server/auth/index.test.ts
Closes #622 
Add a `Learn More` button to the Login screen which connects back to our summer edition website
> Add button on login screen to redirect to summer.vh website

- src/server/mail/templates/accepted.ts
- src/server/mail/templates/confirmed.ts
- src/server/mail/templates/submitted.ts
Update the email templates with the current logo and text for VH Summer Edition 2020
> Update email templates for VH Summer 2020

- src/client/assets/strings.json
> update application deadline

- src/client/assets/application.js
Closes #633 
Add Summer Hackathon waiver to the application
> add summer hackathon waiver

- src/server/mail/templates/accepted.ts
Add sentence about agreeing to the waiver in the acceptance email sent out
> Add sentence about hackathon waiver

- src/client/assets/application.js
- src/client/routes/dashboard/HackerDash.tsx
closes #657 
add address fields to the application and reminder on the hacker dash
> add check-in via vaken

- README.md
> Minor Typographical Fix

- src/client/components/Input/Slider.tsx
Just sets label while leaving option the proper enum
> Fix handling options

- src/client/routes/dashboard/HackerDash.tsx
> same change different branch

- scripts/downloadResumes.ts
I can't test it because I don't seem to have the right env credentials, but this should(?) work to download and rename all hacker resumes for submitted, accepted, and confirmed hackers.
> add resume download script

- src/client/assets/routes.js
- src/common/schema.graphql.ts
- Update the title from `Check-In Events` to `Event Check-in`
- Make `eventScore` not a required section of the Event schema
> Fixes to Check-in Events 

- .eslintrc.js
- .vscode/extensions.json
- .vscode/settings.json
- README.md
- __mocks__/fetch.js
- scripts/makeVolunteer.ts
- src/client/routes/manage/ResumeLink.tsx
- src/client/routes/manage/SponsorHackerView.tsx
- src/client/routes/nfc/Nfc.tsx
Inadvertently messed up previous PR and commit history; rewriting here
> Add deepscan and eslint action 

- package-lock.json
- package.json
https://stackoverflow.com/a/64304022/5041889
> Switch to webpack server from webpack-dev-server

- package-lock.json
- package.json
- src/client/routes/manage/CreateSponsor.tsx
> Replace EMAIL_REGEX with email-validator package

- .github/workflows/ci.yml
- "name" can be a pretty string so I made it one
- upgraded the node thing to v2 cuz why not
> Add pretty job names and update GH actions node dep

- package-lock.json
- package.json
Something on my machine keeps adding it. It's a package that things like the VSCode eslint plugin should use, not one that should be a dep of our repo
> Remove eslint_d

- src/server/nfc/index.ts
line 94 already checks for hackerResult.ok and throws error if not
https://deepscan.io/dashboard/#view=project&tid=7388&pid=9504&bid=261722&prid=&subview=issues
> remove redundant if condition

- scripts/makeOrganizer.ts
> Add exit to makeOrganizer.ts

- .codeclimate.yml
Adds FIXME codeclimate extension - just highlights all the "TODO" in our repo
> Update .codeclimate.yml with extension

- .github/workflows/ci.yml
> Set node-version to .nvmrc for Happo CI job

- __snapshots__/client/routes/login/Login.test.tsx.snap
- src/client/components/Buttons/LeftImgButton.tsx
- src/client/routes/manage/HackerView.tsx
> Fix CenterButtonText color property propagation

- .vscode/settings.json
- src/client/components/Containers/Collapsible.tsx
- src/client/routes/events/ManageEventTypes.ts
- src/client/routes/events/ManageEvents.tsx
- src/client/routes/events/helpers.ts
- src/server/events/index.test.ts
- src/server/events/index.ts
Cleans up manage events page code.
Adds Collapsible divs to separate logical page functions.
Makes pull from calendar button in to right hand as opposed to floating in the middle of a section and makes it red to signify that it will take a while and may result in data changes
> Clean up ManageEvents

- src/client/routes/manage/CreateSponsor.tsx
> Make CreateSponsor refetch modified data

- src/client/app.tsx
- src/client/routes/events/CheckInEvents.tsx
- src/client/routes/events/events.graphql.ts
- src/common/schema.graphql.ts
- src/server/resolvers/MutationResolvers/EventMutationResolvers.ts
Clean up CheckInEvents.tsx code, simplify error paths and remove inline functions in JSX.
Prevent eventScore injection attack by querying DB for actual eventScore.
Note: This could use a caching layer to prevent expensive DB reads every time.
> Clean up CheckInEvents.tsx

- package-lock.json
- package.json
- scripts/devEnv.sh
Global packages are mostly a bad idea (maybe Volta or yarn v2 will make them good ones) and we should discourage them.
> Improve dev env script

- src/client/routes/dashboard/OrganizerDash.tsx
> Add parameter to disable animations in organizer dash

- jest.config.js
Fixed the coverage by restoring the transform.
Before: https://codeclimate.com/repos/5ce5bf4b4e684043df002f15/settings/test_reports/603592fe66ec673fdd000787
After: https://codeclimate.com/repos/5ce5bf4b4e684043df002f15/settings/test_reports/60500e85cf08ff47c4004a22
The Happo error is nonsense. I took a crack at fixing it in #807 but it didn't go well. 
Fixes #806
> Fix Storyshot code coverage

- webpack/webpack.common.js
What changes are made in this PR?
Why are these changes made? Link to Slack etc if necessary. 
> figure out parent directory path

- .github/CONTRIBUTING.md
- README.md
- src/client/routes/application/Application.tsx
PR does 2 things: 
1. In the hacker application, indicates which questions are required w/ an asterisk. (Already in data entity, so just adding conditional logic in UI.)
- Closes #824 
- To replicate, simply run the local instance (`npm run dev`) and visit http://localhost:8081/application. All sections of the application (`Demographic Information`, `Hacker Application`, and the last one, `Shipping`, which you will see has no required questions) should have asterisks indicating when appropriate the required nature of a question.
2. Minor clarifications in documentation in steps for setting up local dev environment
> Add asterisks required qs

- src/client/assets/application.js
- src/client/routes/manage/HackerView.tsx
- src/common/mockObjects.ts
- src/server/mail/templates/accepted.ts
- src/server/mail/templates/confirmed.ts
- src/server/mail/templates/rejected.ts
- src/server/mail/templates/submitted.ts
Fix email image and also remove waiver from application.
> fix broken GCP link for email image and remove waiver

- src/client/assets/application.js
- src/client/components/Input/AutoCompleteTextInput.tsx
- src/client/components/Input/Boolean.tsx
- src/client/routes/application/Application.tsx
- src/client/routes/application/VandyStudentContext.ts
Adds back "Do you want to be contacted about being a volunteer" but only for applicants who select "Vanderbilt University" for school.
> Volunteer question 

- src/server/mail/templates/submitted.ts
> new submit email

- src/client/assets/application.js
- src/client/components/Input/FileInput.tsx
- src/client/routes/manage/HackerView.tsx
- src/client/routes/manage/ResumeLink.tsx
since résumé is the correct spelling, I did not modify the variables or internal fields though, just the strings displayed to the user.
tactical grepping masterrace
> change resume strings to résumé

- src/client/assets/application.js
- src/client/routes/manage/hackers.graphql.ts
- src/client/routes/profile/ProfileConfig.ts
- src/client/routes/profile/user.graphql.ts
- src/common/schema.graphql.ts
- src/server/resolvers/HackerResolver.ts
- src/server/resolvers/MentorResolver.ts
- src/server/resolvers/MutationResolvers/updateApplicationResolver.ts
- src/server/resolvers/UserResolver.ts
What changes are made in this PR?
Why are these changes made? Link to Slack etc if necessary. 
Since we will be running a hybrid in-person/virtual hackathon, this PR updates the hacker application to include a location question.
> Added location question to application

- .eslintrc.js
- src/client/components/Input/FileInput.tsx
- src/server/storage/gcp.ts
Adds a file upload limit to resume upload. Also little spin spin.
> file upload limit, toast error for breaking that limit, loading spinner

- src/client/app.tsx
- src/client/routes/application/Application.tsx
Right now, the validation toasts use brackets to emphasize text. This is kind of sad. Now, we use bolding, like a normal person.
> Make Validation Toasts Look Nice!

- src/client/assets/application.js
> Quick spelling fix

- src/client/components/Buttons/RadioSlider.tsx
- src/client/routes/manage/ActionRenderer.stories.tsx
- src/client/routes/manage/ActionRenderer.tsx
- src/client/routes/manage/SliderInput.tsx
When organizers accept/reject an individual hacker or batch accept/reject, they get prompted by a confirmation dialog (N-57 and N-58)
> Add confirmation for organizer actions

- src/client/routes/dashboard/HackerDash.tsx
This adds spacing between the confirm and decline buttons after a hacker has been accepted (N-56)
> Add spacing between confirm and decline buttons

- src/server/mail/templates/accepted.ts
> Acceptance email
