VandyHacks/vaken

.github/main.workflow

Default detection has been moved out of main action: https://github.com/bencooper222/check-for-node-dep-changes/commit/1e3249760522f56076637d669b6028ce9188a687
So we now have to check ourselves.

Moving out default check to separate action

---

.github/main.workflow

Often breaks for mostly GitHub-Actions-is-in-beta reasons. Putting notifications in a less disruptive channel.

Dependency change notifications in#vaken-status

---

package-lock.json
package.json

Reverts VandyHacks/vaken#120
Upgrading does indeed break things.
Old API: [here](https://github.com/immerjs/use-immer/blob/2f6978410c6ec7a769bf1778ee6fbbed36658db1/index.js)
Old types: [here](https://github.com/immerjs/use-immer/blob/2f6978410c6ec7a769bf1778ee6fbbed36658db1/index.d.ts)
New API + types : [here](https://github.com/immerjs/use-immer/blob/master/src/index.ts)

Revert "Upgrade use-immer: 0.1.0 → 0.3.2 (major)"

---

.circleci/config.yml

So we don't have to constantly bump the version.

Semver node 12.*.* for CI

---

src/client/routes/manage/HackerView.tsx

If no resume provided, field will now not have a link.

Fix empty resume field display

---

src/client/routes/events/ManageEventTypes.ts
src/client/routes/events/ManageEvents.tsx
src/common/schema.graphql.ts
src/server/events/index.test.ts
src/server/events/index.ts

Fixes #477 
After pulling events from Google Calendar, use the `uid` field which is like a unique Google Calendar event object ID to match with events in the database. 
It is now possible to call the `addOrUpdateEvent` resolver to add or update an event with either an ObjectID or a google calendar ID (`gcalID`). However, either must be required or an error is thrown. If both are provided, the google calendar ID is used as the matcher. 
- entity Event: Add 'gcalID' string field. Optional. 
- interface EventUpdate: Add 'gcalID' and 'id' string fields. Both optional.
- input EventUpdateInput: Add 'gcalID' and 'id' string fields. Both optional.
- `addOrUpdateEvent` will perform add or update given an EventUpdate that contain represent a transformed event from GCal or an event queried from the …

Fix Events Matching

---

src/client/routes/nfc/NfcTable.tsx
src/client/routes/nfc/helpers.ts
src/client/routes/nfc/nfc.graphql.ts
src/common/schema.graphql.ts
src/server/nfc/index.test.ts
src/server/nfc/index.ts
src/server/resolvers/index.ts

Adds toast messages (errors) for
- checkin: user already checked in, duplicate nfc id
- event scanning: user already went to event
- unadmit: user has not attended event
- fixes a bug where event not removed from user eventsAttended array on unadmit
- fixes autofocus on invalid user scan
- autofocus back to search box whenever user scans
** some other goodies

Add user feedback for NFC check-ins

---

src/client/routes/events/ManageEventTypes.ts
src/client/routes/events/ManageEvents.tsx
src/client/routes/events/events.graphql.ts
src/client/routes/events/helpers.ts
src/common/schema.graphql.ts
src/server/events/index.ts
src/server/resolvers/index.ts

Solves #493 
Added mutation `removeAbsentEvents` that takes in a list of event object IDs and outputs a number of events removed from the database. All events not in the input list of IDs are removed.
This enables our calendar sync function to be 'hard', meaning that the database will exactly mirror whichever events exist in Google Calendar upon pulling.

Add removeAbsentEvents mutation to hard sync with GCal

---

src/client/assets/routes.js
src/client/routes/events/CheckInEvents.tsx
src/client/routes/events/ManageEventTypes.ts
src/client/routes/events/events.graphql.ts
src/common/schema.graphql.ts
src/server/events/index.test.ts
src/server/events/index.ts
src/server/nfc/index.test.ts
src/server/resolvers/index.ts

Flow: Organizer has to pull events from calendar inside `manage events` once so that the events are created in the db. Then, the `check-in` shows at any time the ongoing events which people can check-in to.
Closes #677

Add Check-in Events funcationality for Hackers

---

.github/workflows/push.yml

Packtracker has never worked right for this repository and has led to a bunch of yellow statuses. Removing it will remove a CI smell.

Remove packtracker.io integration

---

scripts/install.sh

currently, the installation script would overwrite an existing .env which happened with me a couple of times while updating stuff or setting up an installation. 
this checks for its existence before overwriting it.

check if .env exists before overwriting in installation

---

src/client/index.html
webpack.common.js

Fixes #632 
The issue was caused by lacking a real favicon for the site (which broke at some point when webpack stopped bundling the favicon). The favicon reported in the issue was likely cached for the domain.

Use HtmlWebpackPlugin to handle favicon

---

.github/workflows/ci.yml
package.json

The typecheck CI job was doing literally nothing that the build step didn't do. `npm run build:server` also just directly called `tsc`.

Elimate typecheck from CI

---

.babelrc
package.json

All of these proposal plugins are in stage 4 (complete) of the ECMAscript spec. No longer need Babel.
Also saves 3kb on our build.

Eliminate babel plugins that we don't need

---

codegen.json
src/common/schema.graphql.ts
src/server/models.ts
src/server/resolvers/EventResolver.ts
src/server/resolvers/UserResolver.ts

We've had warnings of these for a while. This actually adds them.
I also deleted ApplicationQuestion entirely because it had 3 missing resolvers and no usage. It looks like it's deprecated in favor of `application.js`

Add missing resolvers

---

scripts/populateDb.ts

If you run populateDb in its current state, the page will get stuck on the preloader, and you'll get the following error when you go to the `Manage Hackers` page:
```
[server] {"level":50,"time":1610911928639,"pid":22214,"hostname":"debian",
"message":"Invalid enum value: \"null\" is not in \"
[\"CREATED\",\"DECLINED\",\"STARTED\",\"SUBMITTED\",\"ACCEPTED\",\"CONFIRMED\",\"REJECTED\"]\"",
"locations":[{"line":9,"column":5}],"path":["hackers",13,"status"],"extensions":{"code":"BAD_USER_INPUT","exception":{"stacktrace":["UserInputError: Invalid enum value: \"null\" is not in \"[\"CREATED\",\"DECLINED\",\"STARTED\",\"SUBMITTED\",\"ACCEPTED\",\"CONFIRMED\",\"REJECTED\"]\"","    at /home/.../vaken/src/server/resolvers/helpers.ts:37:10","    at status …
```

Fix populateDb

---

.env.template

Given we recommend Atlas in the Contributing guide, it is better to have the sample URL represent that so the user knows it needs to be changed. If an advanced user has mongo locally, then they'll know it needs to be changed anyway but this would be useful to make it less confusing for newer folks.
Motivation: saw someone trying to set up Vaken locally.

Add sample atlas URL to sample env

---

package-lock.json
package.json
webpack.common.js

It turns out that loading from a CDN is incompatible with `helmet`, which sets content security policies disallowing loading scripts from other domains.
It's possible to make them coexist, but I'm not a security expert and the likelihood that I mess up the security configuration and expose everyone's personal information to attackers is... high, so we'll take the bundle hit and just bundle React and React-DOM.

Revert loading React from cdn

---

.storybook/preview.js
package-lock.json
package.json
src/client/routes/dashboard/OrganizerDash.stories.tsx
src/client/routes/dashboard/OrganizerDash.tsx
src/common/mockObjects.ts

Noticed 3 issues (2 unique) with our Storyshots [here](https://happo.io/a/553/p/683/compare/9922e7935cd61988227d34e0194472fe3ddbbabc/5b4b70bca88b786ccddba86de5ef86524581a9a3).
- First seemed to have been caused by fairly innocuous shifting? Will approve this one manually
- Second was caused by mocked check-in date always being right now. Fixed this in this PR. Will approve in Happo.
Also added the ability to log in components and see the logs in the Storybook actions console. 'Tis great: https://github.com/storybookjs/storybook-addon-console/

Fix Storyshot inconsistencies 

---

package-lock.json
package.json

https://github.com/storybookjs/storybook/issues/14497 and https://github.com/storybookjs/storybook/issues/14403
tl;dr: Happo stopped working because `npm run build-storybook` was failing after #818 upgraded webpack to a new minor version and threw us into the weird implicit hoisting mess described below.
Theoretically this is a workaround and can be removed after https://github.com/storybookjs/storybook/issues/14403 is resolved, but there is no sign of when that'll happen
Deep technical reasons from the linked issue for why this fails:
> If npm hoists dotenv-webpack 6.0.4 to the node_modules root, everything works fine. However, if npm hoists dotenv-webpack 1.8, and the user has a .env file present, start-storybook fails to run.
>
> Unless the user is already pinning dotenv-webpack, the …

Add dotenv-webpack to work around storybookjs/storybook#14403

---

.github/workflows/push.yml
package-lock.json
package.json

Update dependencies and also change the workflow script's npm audit step to use --production instead of --only=prod (which was still allowing dev dependencies to fail the build for some reason)

Fix dependencies

---

src/client/routes/application/Application.tsx

Currently, you can submit an application with your first name, last name, phone #, school, major as just a bunch of spaces.
This PR prevents that at least for required fields.
We should still have some validation for non-required fields but I am not sure of the best way to go about that.
fixes 4 of Nisala's bugs.

Trim whitespace for required questions

---

src/client/components/Containers/Collapsible.tsx

fixes vaken bug N-37 
full discourse: https://www.notion.so/vandyhacks/Vaken-for-VH-VIII-6a21b4b876494225bda265aa5d185163#0b9b186a5fe842a4bbf6a4d21fb5181d
since we have an up arrow, I just added css to flip it.

flip disclosure triangle 180deg

---

src/client/components/Input/FileInput.tsx

ideally shouldn't have been hardcoded
also I was looking for a button but it appears the upload a resume "button" looks like one but isn't actually one.

modify glow to the submit button glow

---

src/client/components/Input/Slider.tsx

This makes the white blur less visible, and makes the radio buttons square instead of every option being rounded and having gaps. It would be nice to have the entire slider have rounded corners to get rid of the gaps, but I wasn't able to figure out how.

Weaken white blur

---

src/client/assets/routes.js
src/client/routes/dashboard/OrganizerDash.tsx
src/client/routes/manage/hackers.graphql.ts

The organizer dash no longer throws an error. Instead, useful charts about cumulative t-shirt sizes, application status, and gender are shown.

Recreating organizer dashboard pr

---

src/client/routes/dashboard/HackerDash.tsx

This displays a confirmation alert before the user accepts or rejects their offer (N-59).
My local setup can't accept or reject offer. I would recommend you make sure it's just a configuration issue on my end.

Add confirmation before accepting or rejecting offer
